services:
  - type: web
    name: tire-shop-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        value: manikanta_tire_secret_123

      - key: DATABASE_URL
        fromDatabase:
          name: tire-shop-db
          property: connectionString

      - key: ALLOWED_ORIGINS
        value: https://your-frontend-name.vercel.app

databases:
  - name: tire-shop-db
    plan: free
    databaseName: tireshop
    user: tireshop